[Tests] Adapt FastThreadLocalStateCleaner to Netty changes: suppress excessive logging (#15269)
- suppresses this warning log entry:
  java.lang.RuntimeException: It's not thread-safe to get 'threadLocalMap' which doesn't belong to the caller thread
    at io.netty.util.concurrent.FastThreadLocalThread.threadLocalMap(FastThreadLocalThread.java:80) ~[netty-common-4.1.76.Final.jar:4.1.76.Final]

(cherry picked from commit 2e5309cb74895cf7a635ee2652dc7cc77a388e72)